name: Create ServiceNow POC Files

on:
  workflow_dispatch:

jobs:
  create-servicenow-poc-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create folder structure
        run: |
          mkdir -p servicenow-integration/incident-automation-servicenow

      - name: Create reassign-incident.yml
        run: |
          cat > servicenow-integration/incident-automation-servicenow/reassign-incident.yml << 'EOF'
          ---
          - name: Re-assign Incident
            hosts: localhost
            gather_facts: no

            vars:
              ansible_python_interpreter: /usr/bin/python3
              servicenow_instance: ""
              servicenow_user: ""
              servicenow_password: ""
              INC_SysID: ""
              requestor_email: ""
              reassign_group: ""

            tasks:
              - name: Re-assign the incident
                uri:
                  url: "{{ servicenow_instance }}/api/now/table/incident/{{ INC_SysID }}"
                  method: PATCH
                  user: "{{ servicenow_user }}"
                  password: "{{ servicenow_password }}"
                  headers:
                    Accept: "application/json"
                    Content-Type: "application/json"
                  body: |
                    {
                      "assigned_to": "",
                      "work_notes": "[code] {{ mail_subject_failure | regex_replace('\r?\n', '') | safe }} [/code]",
                      "assignment_group": "{{ reassign_group }}"
                    }
                  body_format: json
                  validate_certs: no
                register: result_reassign

              - name: Display result of re-assigning the incident
                debug:
                  var: result_reassign

              - name: Sending a HTML email
                community.general.notification.mail:
                  host:
                  port:
                  from:
                  to: "{{ requestor_email }}"
                  cc:
                  subject: Ansible Automation | Service Restart - Unable to connect to server
                  subtype: html
                  body: |
                    Hi Windows Team,<br><br>
                    Please find below failure details.<br><br>
                    {{ mail_subject_failure | regex_replace('\r?\n', '') | safe }}.<br><br>
                    Incident : <b>{{ incident_number }}</b> has been reassigned to <b>"{{reassign_group}}"</b> for further investigation.<br><br>
                    <br>Regards<br>
                    <b>Ansible Automation Team</b>
                delegate_to: localhost
          EOF

      - name: Create update-incident.yml
        run: |
          cat > servicenow-integration/incident-automation-servicenow/update-incident.yml << 'EOF'
          ---
          - name: Update ServiceNow Incident
            hosts: localhost
            gather_facts: no

            vars:
              ansible_python_interpreter: /usr/bin/python3
              servicenow_instance: ""
              servicenow_user: ""
              servicenow_password: ""
              INC_SysID: ""
              assigned_to: ""

            tasks:
              - name: Retrieve incident details
                uri:
                  url: "{{ servicenow_instance }}/api/now/table/incident/{{ INC_SysID }}"
                  method: GET
                  user: "{{ servicenow_user }}"
                  password: "{{ servicenow_password }}"
                  headers:
                    Accept: "application/json"
                  validate_certs: no
                register: incident_details

              - name: Set incident number as a stat
                set_stats:
                  data:
                    incident_number: "{{ incident_details.json.result.number }}"

              - name: Retrieve requestor email
                uri:
                  url: "{{ servicenow_instance }}/api/now/table/sys_user/{{ incident_details.json.result.caller_id.value }}"
                  method: GET
                  user: "{{ servicenow_user }}"
                  password: "{{ servicenow_password }}"
                  headers:
                    Accept: "application/json"
                  validate_certs: no
                register: requestor_details

              - name: Set requestor email as a stat
                set_stats:
                  data:
                    requestor_email: "{{ requestor_details.json.result.email }}"

              - name: Change incident status to Work in Progress and assign ticket
                uri:
                  url: "{{ servicenow_instance }}/api/now/table/incident/{{ INC_SysID }}"
                  method: PATCH
                  user: "{{ servicenow_user }}"
                  password: "{{ servicenow_password }}"
                  headers:
                    Accept: "application/json"
                    Content-Type: "application/json"
                  body: |
                    {
                      "assigned_to": "{{ assigned_to }}",
                      "state": "2"
                    }
                  body_format: json
                  validate_certs: no
                register: result

              - name: Display result
                debug:
                  var: result
          EOF

      - name: Create restart-windows-service.yml
        run: |
          cat > servicenow-integration/incident-automation-servicenow/restart-windows-service.yml << 'EOF'
          ---
          - name: Restart a Windows service without using win_service module
            hosts: all
            vars:
              service_name: ""

            tasks:
              - name: Check connection to the host using PowerShell
                ansible.windows.win_shell: |
                  if (Test-Connection -ComputerName {{ IP_Address }} -Count 1 -Quiet) {
                    exit 0
                  } else {
                    exit 1
                  }
                register: ping_result
                ignore_unreachable: true
                failed_when: false

              - name: Set failure variable if unable to connect
                set_fact:
                  connection_status: "Failed to connect to {{ device_name }} {{ IP_Address }}"
                when: ping_result.rc != 0

              - name: Set success variable if able to connect
                set_fact:
                  connection_status: "Successfully connected to {{ IP_Address }}"
                when: ping_result.rc == 0

              - name: Set connection status for next template
                set_stats:
                  data:
                    mail_subject_failure: "{{ connection_status }}"

              - name: Fail if unable to connect to the host
                ansible.builtin.fail:
                  msg: "Unable to connect to the requested IP: {{ IP_Address }}"
                when: ping_result.rc != 0

              - name: Restart the service
                win_shell: |
                  $errorMessage = ""
                  try {
                      $service = Restart-Service -Name "{{ service_name }}" -PassThru -ErrorAction Stop
                      $status = $service.Status
                  } catch {
                      $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue
                      if ($null -eq $service) {
                          $service = Get-WmiObject -Class Win32_Service -Filter "Name='{{ service_name }}'"
                      }
                      $status = "Unsuccessful"
                      $errorMessage = $_.Exception.Message
                  }
                  $html = "<table style='border: 1px solid; border-collapse: collapse;'><tr style='background-color: blue;'><th style='border: 1px solid; color: white;'>Status</th><th style='border: 1px solid; color: white;'>Name</th><th style='border: 1px solid; color: white;'>DisplayName</th>"
                  if ($errorMessage) { $html += "<th style='border: 1px solid; color: white;'>Error</th>" }
                  $html += "</tr><tr><td style='border: 1px solid;'>$status</td><td style='border: 1px solid;'>$($service.Name)</td><td style='border: 1px solid;'>$($service.DisplayName)</td>"
                  if ($errorMessage) { $html += "<td style='border: 1px solid;'>$errorMessage</td>" }
                  $html += "</tr></table>"
                  $html
                register: win_service_restart
                when: ping_result.rc == 0

              - debug:
                  msg: "{{ win_service_restart.stdout }}"
                when: ping_result.rc == 0

              - name: Set data for next template
                set_stats:
                  data:
                    mail_subject_success: "{{ win_service_restart.stdout }}"
                when: ping_result.rc == 0
          EOF

      - name: Create trigger-awx-workflow.yml
        run: |
          cat > servicenow-integration/incident-automation-servicenow/trigger-awx-workflow.yml << 'EOF'
          ---
          - name: Trigger Ansible Workflow Job Template
            hosts: localhost
            gather_facts: no

            vars:
              tower_host: ""
              tower_username: ""
              tower_password: ""
              workflow_template_id: ""
              service_name: ""
              INC_SysID: ""
              INC_Desc: ""

            tasks:
              - name: Extract service_name from INC_Desc
                set_fact:
                  service_name: "{{ (INC_Desc | regex_findall('Service Name: *([^\\r\\n]+)'))[0] }}"

              - name: Extract device_name from INC_Desc
                set_fact:
                  device_name_list: "{{ (INC_Desc | regex_findall('Device: *([^\\r\\n]+)')) }}"

              - name: Set device_name
                set_fact:
                  device_name: "{{ device_name_list[0] }}"

              - name: Extract IP address from INC_Desc
                set_fact:
                  IP_Address: "{{ (INC_Desc | regex_findall('IP address:\\s*(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})'))[0] }}"

              - name: Get AWX API token
                uri:
                  url: "{{ tower_host }}/api/v2/tokens/"
                  method: POST
                  user: "{{ tower_username }}"
                  password: "{{ tower_password }}"
                  force_basic_auth: yes
                  status_code: 201
                  body_format: json
                  headers:
                    Content-Type: "application/json"
                  body:
                    description: "Token for triggering workflow"
                register: token_response

              - name: Extract token
                set_fact:
                  awx_token: "{{ token_response.json.token }}"

              - name: Trigger the workflow job template
                uri:
                  url: "{{ tower_host }}/api/v2/workflow_job_templates/{{ workflow_template_id }}/launch/"
                  method: POST
                  headers:
                    Authorization: "Bearer {{ awx_token }}"
                    Content-Type: "application/json"
                  body_format: json
                  body:
                    extra_vars:
                      service_name: "{{ service_name }}"
                      INC_SysID: "{{ INC_SysID }}"
                      IP_Address: "{{ IP_Address }}"
                      device_name: "{{ device_name }}"
                  status_code: 201
                register: workflow_result

              - name: Display workflow result
                debug:
                  var: workflow_result

              - name: Display workflow job URL
                debug:
                  msg: "Workflow job URL: {{ workflow_result.location }}"
          EOF

      - name: Create incident-management.yml
        run: |
          cat > servicenow-integration/incident-automation-servicenow/incident-management.yml << 'EOF'
          ---
          - name: Service Restart and Incident Management
            hosts: localhost
            gather_facts: no

            vars:
              ansible_python_interpreter: /usr/bin/python3
              servicenow_instance: ""
              servicenow_user: ""
              servicenow_password: ""
              INC_SysID: ""
              incident_number: ""
              requestor_email: ""
              service_name: ""
              close_code: "Solution provided"
              close_notes: "Service {{ service_name }} has been successfully restarted"
              assigned_to: ""
              reassign_group: ""

            tasks:
              - name: Check if service restarted successfully
                set_fact:
                  service_status: "{{ 'Running' in mail_subject_success }}"

              - name: Close the incident if service restarted successfully
                when: service_status
                uri:
                  url: "{{ servicenow_instance }}/api/now/table/incident/{{ INC_SysID }}"
                  method: PATCH
                  user: "{{ servicenow_user }}"
                  password: "{{ servicenow_password }}"
                  headers:
                    Accept: "application/json"
                    Content-Type: "application/json"
                  body: |
                    {
                      "state": "6",
                      "close_code": "{{ close_code }}",
                      "work_notes": "[code] {{ mail_subject_success | regex_replace('\r?\n', '') | safe }} [/code]",
                      "close_notes": " {{close_notes}} "
                    }
                  body_format: json
                  validate_certs: no
                register: result_close

              - name: Re-assign the incident if service restart failed
                when: not service_status
                uri:
                  url: "{{ servicenow_instance }}/api/now/table/incident/{{ INC_SysID }}"
                  method: PATCH
                  user: "{{ servicenow_user }}"
                  password: "{{ servicenow_password }}"
                  headers:
                    Accept: "application/json"
                    Content-Type: "application/json"
                  body: |
                    {
                      "assigned_to": "",
                      "work_notes": "[code] {{ mail_subject_success | regex_replace('\r?\n', '') | safe }} [/code]",
                      "assignment_group": "{{ reassign_group }}"
                    }
                  body_format: json
                  validate_certs: no
                register: result_reassign

              - name: Display result of closing the incident
                when: service_status
                debug:
                  var: result_close

              - name: Display result of re-assigning the incident
                when: not service_status
                debug:
                  var: result_reassign

              - name: Set email subject and body based on service status
                set_fact:
                  email_subject: >-
                    {% if service_status %}
                    {{ incident_number }} | Ansible Automation | Service Restarted [Successfully]
                    {% else %}
                    {{ incident_number }} | Ansible Automation | Service Restart [Unsuccessful]
                    {% endif %}
                  email_body: >-
                    {% if service_status %}
                    Hi Team,<br><br> The <b>{{ service_name }}</b> service was <font color="green"><b>Successfully</b></font> restarted.<br><br>
                    {{ mail_subject_success | regex_replace('\r?\n', '<br>') | safe }}
                    Incident : <b>{{ incident_number }}</b> has been closed.<br><br>
                    <br>Regards,<br><b>Ansible Automation</b>
                    {% else %}
                    Hi Team,<br><br> The <b>{{ service_name }}</b> service restart was <font color="red"><b>Unsuccessful</b></font>.<br><br>
                    {{ mail_subject_success | regex_replace('\r?\n', '<br>') | safe }}
                    Incident : <b>{{ incident_number }}</b> has been reassigned to <b>"{{reassign_group}}"</b>.<br><br>
                    <br>Regards,<br><b>Ansible Automation</b>
                    {% endif %}

              - name: Sending a HTML email
                community.general.notification.mail:
                  host:
                  port:
                  from:
                  to: "{{ requestor_email }}"
                  subject: "{{ email_subject }}"
                  subtype: html
                  body: "{{ email_body }}"
                delegate_to: localhost
          EOF

      - name: Commit and push all files
        run: |
          git add .
          git diff --cached --quiet || git commit -m "feat(servicenow): add incident automation POC files"
          git push origin dev
